---
collections:
  - name: community.general
  - name: community.kubernetes
roles:
  - name: ansible-role-forgeops
    src: git@github.com:patrickschlaepfer/ansible-role-forgeops.git
    version: origin/main
    scm: git